apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "truesight.fullname" . }}-api
  labels:
    {{- include "truesight.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      {{- include "truesight.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "truesight.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "build/index.js"]
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "truesight.fullname" . }}
            - configMapRef:
                name: {{ include "truesight.fullname" . }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
