apiVersion: v1
kind: Service
metadata:
  name: {{ include "truesight.fullname" . }}-api
  labels:
    {{- include "truesight.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "truesight.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
