apiVersion: v1
kind: Service
metadata:
  name: {{ include "openerrata.fullname" . }}-api
  annotations:
    {{- if .Values.service.skipAwait }}
    pulumi.com/skipAwait: "true"
    {{- end }}
  labels:
    {{- include "openerrata.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "openerrata.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
