{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openerrata.fullname" . }}-default-deny-ingress
  labels:
    {{- include "openerrata.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openerrata.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openerrata.fullname" . }}-api-allow-ingress
  labels:
    {{- include "openerrata.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openerrata.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
{{- end }}
